### ISSUE TITLE
Install Honeycomb agent on my dev machine

### ISSUE THREAD

**Issue by dov0211** [honeycombio/honeytail#104]
Hi
I am trying to get the honecomb agent to my MAC OS for some testing, can you help me with the command, 
as when i try doing the following
wget -q -O honeytail https://honeycomb.io/download/honeytail/linux/1.591 && \
>     echo 'bab8fa43df7661912ea246affe8a273c87a163f17c57efd30d67d01ce6d22244  honeytail' | sha256sum -c && \
>     chmod 755 ./honeytail

-bash: wget: command not found

**Comment by patrickbray** [comment]
@dov0211 you can install wget via homebrew:

```
brew install wget
``` 

Though it looks like this binary will not run on osx 

```
$ ./honeytail
zsh: exec format error: ./honeytail
$ file ./honeytail
./honeytail: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, with debug_info, not stripped
```

**Comment by JamieDanielson** [comment]
As mentioned in the previous comment, the initial issue reported was due to the missing wget package that needed to be installed from homebrew.

Regarding the follow-up issue of running the installed agent, additional configuration must be set to run the agent. Check out our [docs](https://docs.honeycomb.io/getting-data-in/integrations/honeytail/#launch-the-agent), which are very likely to have been updated since this issue was raised (sorry for the delay on this).

Use a config file and run `honeytail -c /etc/honeytail/honeytail.conf`, passing the path of the config that includes `ParserName`, `WriteKey`, `LogFiles`, and `Dataset`.

Alternatively, try running with command line flags, like so:
```
honeytail \
    --writekey=YOUR_API_KEY \
    --parser=json \
    --dataset='My App' \
    --file=/var/log/app/myapp.log
```
