### ISSUE TITLE
[Feature Request] add honeytail command line flag to handle parser failures

### ISSUE THREAD

**Issue by decimalator** [honeycombio/honeytail#143]
Most parsers I have inspected will throw away logs that don't parse:

https://github.com/honeycombio/honeytail/blob/6969f1a25aa24bb50922a86dc8fca19ba35c228f/parsers/htjson/htjson.go#L76

We have to work with a lot of third party tools that log in stupid ways that we can't change, so it would be helpful to have a command line flag that allows logs that can't be parsed to still go to Honeycomb but throw the whole line into a field of your choosing, maybe `log` by default to sort of match the way the `nop` parser works. 

Instead of skipping lines that fail to parse when running in this mode honeytail would parse normally for lines that match, but would generate an event for the log line with the entire contents of the line in the `log` field, or add an option to choose which field to be the fallback field for parser failures.

The other benefit of this would be an in-dataset searchable record of parser failures to help us improve our agent configurations.

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
