### ISSUE TITLE
Postgres parsing regular expressions are broken

### ISSUE THREAD

**Issue by Spindel** [honeycombio/honeytail#149]
In postgresql, databases, usernames and more can contain characters outside your chosen regular expressions for slow query logs

Compare:
`slowQueryHeader = `\s*(?P<level>[A-Z0-9]+):\s+duration: (?P<duration>[0-9\.]+) ms\s+(?:(statement)|(execute \S+)): `

With the log line:
`2020-03-12 09:22:12.102 CET [12422] admin.moodio.se@moodio.se LOG:  duration: 8618.372 ms  plan:`

This makes honeytail miss _all_ log events in our database.

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
