### ISSUE TITLE
honeytail should be able to backfill directly from gzipped logs

### ISSUE THREAD

**Issue by toshok** [honeycombio/honeytail#21]
Shouldn't be terribly hard, and would make things easier on users to not have to gunzip, backfill, gzip.

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
