### ISSUE TITLE
nginx tail doesn't appear to support http_authorization

### ISSUE THREAD

**Issue by miketheman** [honeycombio/honeytail#35]
As recommended [by the installer here](https://github.com/honeycombio/honey_installers/blob/28314bad7d53a5d9bae15c711ef63993282ab710/nginx_installer/nginx_installer.py#L26), adding `$http_authorization` to a parser to a Basic secured site fails to parse.

I could not find examples in the parser's tests to confirm that this is intentional.

Removing the `$http_authorization` directive from the config allows the line to be parsed.

Here's a scrubbed example of a log line with basic auth that fails parsing:

```
logline="1.2.3.4 - myserver [17/Jan/2017:16:39:59 +0000] \"GET /2016/slides/slide-4.jpg HTTP/1.1\" 200 79974 \"https://example.com/2016/slides\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36\" \"-\" server.example.com 667 - Basic RandomString 0.294 80412 server.example.com"
```

**Comment by maplebed** [comment]
The section of the log line containing the basic auth must be in quotes. Because basic auth expands to one (when absent) or two (when present) fields in the line, it breaks the parsing. Putting it in double quotes gives the regex something to anchor against.

I will update the docs to make this more clear, but marking this WNF for now since it's docs instead of code.

**Comment by miketheman** [comment]
Then it's not only docs, it's installer code. Feel free to open the appropriate issue there and reference this one for clarity.

**Comment by maplebed** [comment]
ah! yes, you linked to that. I'll open an issue there. Thanks.
