### ISSUE TITLE
mysql parser does not support unix socket to fetch extra info and connection ID

### ISSUE THREAD

**Issue by amonakhov** [honeycombio/honeytail#92]
1. When specifing mysql.host as a unix socket, i.e.:
`mysql.host=@unix(/var/run/mysqld/mysql.sock)`
honeytail produces an error.

2. Also in mysql slow log format there is a connection IDentifier is passed along with user and client host attributes. Honeytail just gets rid of Id completly. It would be nice to get support of that as well.
```
# administrator command: Prepare;
# User@Host: root[root] @  [10.0.1.76]  Id: 325920
...
```

Here is patch for support all mentioned above:
[mysql.txt](https://github.com/honeycombio/honeytail/files/1730987/mysql.txt)

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
