### ISSUE TITLE
Weird behavior for hosted_on attribute for mysql parser

### ISSUE THREAD

**Issue by amonakhov** [honeycombio/honeytail#93]
It looks from the code that hosted_on does not seem to work on most self-hosted servers (not RDS). 

Probably hosted_on should contain `hostname` instead of `basedir` variable value. Or at least work for not just RDS instances.

It would be good data value to have hosted_on (or other attribute) which represents a hostname of the server because there might be more than just one server honeytail will parse logs from.

Here we have a patch with our suggestion:
[mysql-hosted.txt](https://github.com/honeycombio/honeytail/files/1731019/mysql-hosted.txt)

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
